#!/bin/bash -eu

# shellcheck disable=SC1091
. debian/debian.env

#
# Turn off strong stack protection as it requires gcc 4.9+
#
sed -i -e 's/^.*CONFIG_CC_STACKPROTECTOR_REGULAR.*$/CONFIG_CC_STACKPROTECTOR_REGULAR=y/' -e 's/^CONFIG_CC_STACKPROTECTOR_STRONG.*$/# CONFIG_CC_STACKPROTECTOR_STRONG is not set/' "${DEBIAN}/config/config.common.ubuntu"
sed -i 's/CONFIG_CC_STACKPROTECTOR_STRONG/CONFIG_CC_STACKPROTECTOR_REGULAR/' "${DEBIAN}/config/annotations"

# Disable ZFS as we have no tooling in trusty to mount these.
sed -i -e 's/^\(do_zfs[ \t]*=[ \t]\)true\(.*\)$/\1false\2/' "${DEBIAN}/rules.d/"*.mk

rm -f "${DEBIAN}/d-i/kernel-versions"
